### PR TITLE
Just using defined

### PR DESCRIPTION
**Pull request by kbrock**
I would imaging that just using `defined?` would be sufficient to know if a gem was imported without
resorting to testing whether it is a `class` or `module`.

Well, that is my interpretation of the code that introduced this method: af73d1255473af0cff9c5f02b429a49c755a0597

But it is very possible that I don't understand the nuances that you were targeting.
Thanks

### CODE REVIEW

**Comment by SamSaffron** [comment]
Probably, but this is a very big change I worry that we are missing an edge case or 2

**Comment by kbrock** [comment]
fair enough - but the original code looks like it called this instead of `defined?(ActiveRecord)`
Maybe the original code would have worked with this, but possibly the newer code would not.

Just close it then?

**Comment by SamSaffron** [comment]
yeah going to close this ... worried it is too risky

**Comment by kbrock** [comment]
thanks

**Pull request closed without merging**
