### PR TITLE
make _profilin cookie httpOnly and secure if request is over ssl

### PR DESCRIPTION
**Pull request by gregmolnar**

### CODE REVIEW

**Comment by SamSaffron** [comment]
are we fussing with the cookie from the client anywhere? Overall I am fine with this change.

**Comment by gregmolnar** [comment]
The reason I propose this change is, when you use miniprofiler in production, it is advised to follow security best practices with the cookies, even though there is nothing sensitive in this cookie (I should've mentioned this at the first comment).

**Comment by gregmolnar** [comment]
@SamSaffron Is there any chance to merge this?

**Comment by SamSaffron** [comment]
I guess we can try this, will merge it now.

**Pull request merged**
