### PR TITLE
Organize controller

### PR DESCRIPTION
**Pull request by kbrock**
I'd like to understand the main controller loop better (i.e.: `def call()`)

This PR is the start of extracting a command / factory pattern. A lot of places in the code are very tight. This sticks with the functional approach, focusing on defining the boundaries and parameters of the various commands.

Does this look like a good course of action or a bit too disruptive?
Any special hints before I go too far?

Thanks

### CODE REVIEW

**Comment by SamSaffron** [comment]
I am technically ok with this work, I just am very very very afraid of regressions, can you ensure there is full coverage for everything you are changing?

**Comment by seanlinsley** [comment]
This needs to be rebased

**Comment by kbrock** [comment]
I'm intimidated by adding tests here.

**Comment by SamSaffron** [comment]
closing this for now as too scared to change it

**Pull request closed without merging**
