### PR TITLE
Update README.md (authorization_mode config option details)

### PR DESCRIPTION
**Pull request by procommerz**

### CODE REVIEW

**Comment by seanlinsley** [comment]
This should be an easy merge. @SamSaffron?

**Comment by SamSaffron** [comment]
Sorry I held back here cause we have: 

https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler_rails/railtie.rb#L35-L37

This is only needed if you are running in Dev OR not in Rails. Readme should clarify all of this stuff.

**Comment by olleolleolle** [comment]
Would a line like this complete this PR?

"This is needed in all Rails environments _except_ development and test."

**Comment by SamSaffron** [comment]
yes please :)

**Comment by SamSaffron** [comment]
thanks I added a note to clarify

**Pull request closed without merging**
