### PR TITLE
Use base.url_path as fallback for settings path if no url can be created from environment

### PR DESCRIPTION
**Pull request by stiller-leser**
This is indirectly directed to #60 and solved our issues.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Can you do a test for this? also squash down the 4 commits?

**Comment by stiller-leser** [comment]
I'll have a look again. Will definetly squash. How do you want the test? Just check whether path=base_url if path is nil?

**Comment by kbrock** [comment]
Is it possible to rebase instead of merging onto your changes?

This PR looks mammoth

**Comment by stiller-leser** [comment]
@kbrock Yep most definetly. I apologize for the mess above. I switched machines and chaos ensued. I'll close this PR an open a new clean one.

Have a good start into the new week!

**Pull request closed without merging**
