### PR TITLE
Capture parameters for sql

### PR DESCRIPTION
**Pull request by kbrock**
Hi Sam/All,

Looks like the query parameters are not captured.
Not sure if this is by design, or an oversight.

Would you like a configuration parameter to turn this on or off.
Or some extra protections to limit passwords or large values?

Thanks
Keenan

### CODE REVIEW

**Comment by SamSaffron** [comment]
there is a reason for this, imagine you are inserting a huge file or bit of text, ideally we should truncate params so we don't store giant blobs in redis.

**Comment by kbrock** [comment]
I can add tests, but is this closer to what you envisioned?

**Comment by SamSaffron** [comment]
In principle I am ok with this, but we need to work out the UI and tests need to be added

We also need to confirm there is no noticeable perf impact.

**Comment by kbrock** [comment]
Any suggestions on measuring the overhead that is introduced?
On my computer, benchmarks vary so much for ruby only micro tests. Not sure if I could detect issues introduced with an integration test.

If I pulled off the first commit into a separate PR, could we merge that? It would not do anything for users. But it makes my local fork just a little closer to the master version.

I hadn't looked into implementing this in the ui. Locally, I'm using a ruby ui to access the data. It is easier for me to run a method a number of times and then generate a single table with correlated results.

**Comment by SamSaffron** [comment]
Lets make this opt-in default off, then I am find to merge it in.

**Comment by kbrock** [comment]
Hi Sam

I made this default to disabled.
Tried to make the placement of the `params` parameter the most logical, but it was tricky.

Is this closer to what you had in mind?

--Keenan

**Comment by SamSaffron** [comment]
Yes, this looks good, can you also add some doco into the readme?

**Comment by pgiblock** [comment]
Is this feature supposed to work? I noticed it is an undocumented feature. I set:
```
Rack::MiniProfiler.config.max_sql_param_length == 100
```
but unfortunately, I do not see any parameter values (and the JSON of the each result has `parameters=null`)

**Comment by kbrock** [comment]
The data stored in redis has the parameters. Not sure how it translates to the rest of the system

**Pull request merged**
