### PR TITLE
FIX: string interpolation was breaking ie11 support

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Comment by jjaffeux** [comment]
WIP!

I asl need to remove fat arrow and spread

**Comment by SamSaffron** [comment]
should we just run our current include.js through babel and check that in (with minor touchups) ?

**Comment by jjaffeux** [comment]
This is what I did here, manually.

**Comment by OsamaSayegh** [comment]
Ok I've made some changes and it should be now 100% compatible with IE11 with minimal costs.

Notable changes:

* I replaced the spread operator `...` with a simple function `toArray` that loops through `NodeList` using a for loop and returns a normal array. That way we don't need to polyfill `Symbol`.

* Added a small polyfill for `Element.closest` (and `Element.matches` which is needed for `closest` polyfill).

* `forEach` isn't available for `NodeList` in IE11, so I wrapped all `querySelectorAll` calls that are chained to `forEach` with the `toArray` function that I wrote to replace spread operators.

* `Element.remove` isn't available in IE11, so I replaced it with `element.parentElement.removeChild(element)`.

Can you review @jjaffeux @SamSaffron please?

**Comment by SamSaffron** [comment]
> Added a small polyfill for Element.closest (and Element.matches which is needed for closest polyfill).

I would prefer if the polyfill was done a bit differently, don't touch Element.closest, instead use a helper function to do it for now. I worry that polyfills fight with other polyfills so I would prefer to be isolated.

**Comment by SamSaffron** [comment]
overall this is looking great to me, be sure to also pass it through prettier.

**Comment by SamSaffron** [comment]
cool I am merging this in and cutting a release!

**Pull request merged**
