### PR TITLE
Removes use of eval() as JSON is very well supported now

### PR DESCRIPTION
**Pull request by jjaffeux**
We can now safely rely on JSON being available:

https://caniuse.com/#feat=json

### CODE REVIEW

**Comment by SamSaffron** [comment]
hmmm everything about this is strange... the duplication.. the json... why even do json here to get a bunch of ids we should simply split on `,` and be done?

**Comment by SamSaffron** [comment]
@OsamaSayegh can you have a look at ^^^^

**Comment by jjaffeux** [comment]
> @OsamaSayegh can you have a look at ^^^^

Sorry thought I had answered this...

So anyways I didn't want to refactor any deep design of rack-mini-profiler with this commit, but essentially, this is coming from:

https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler/profiler.rb#L383

Which is basically serializing an array of ids using `JSON.generate` https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler/profiler.rb#L589

So we get somethings like : 

```
X-Miniprofiler-Ids: ["4spklr7d0rii7l9ylmoh","t00hjk19bvuplp9l2fgi","f4hp116ac05db1z5ospi","xzim6sud1g2nhvxqx4hi","nv9q4578gqbs0xpq8juh"]
```
And then use `JSON.parse` on the client to deserialize it, so we could do a ids.join(',') on the ruby side and a split(",") on the client side, that would work too, I'm unsure on the reasons if this decisions at the beginning though. It seems like there was a reason, or why go through the specific IE case otherwise?

**Comment by SamSaffron** [comment]
I say we change the header, it seems a bit pointless to do all this work.

**Comment by coding-horror** [comment]
Should @OsamaSayegh  be looking at this? I don't like that it is stalled

**Comment by SamSaffron** [comment]
Sure, once Osama is done with keyboard shortcuts he can sort this one out.

**Comment by OsamaSayegh** [comment]
I can't push to this PR, so I've included this change in https://github.com/MiniProfiler/rack-mini-profiler/pull/399. Thanks @jjaffeux

**Comment by jjaffeux** [comment]
Cool, closing this then! thanks

**Pull request closed without merging**
