### PR TITLE
Add total sql count

### PR DESCRIPTION
**Pull request by zaru**
Fix to display SQL execution count on button.

I think that it is easier to improve by seeing the execution count of SQL together with the execution time.

Thank you for the awesome gem.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Can I see a screenshot?

**Comment by zaru** [comment]
@SamSaffron 
42985914-627d8104-8c2e-11e8-9f77-2d9cf6180302

**Comment by SamSaffron** [comment]
OK so let's make this optional, default off, be sure to add doco to the
readme.

**Comment by zaru** [comment]
@SamSaffron 
Thank you for confirmation.
Changed to option.

```
Rack::MiniProfiler.config.show_total_sql_count = true
```

**Comment by SamSaffron** [comment]
cool I think this is fine!

**Pull request merged**
