### PR TITLE
Update misleading comment in railtie.rb

### PR DESCRIPTION
**Pull request by rthbound**
There is no #post_authorize_cb

The comment here should likely be amended (or removed entirely if the statement is no longer true).

### CODE REVIEW

**Comment by SamSaffron** [comment]
the comment should point to `Rack::MiniProfiler.authorize_request` , if called in prd it enables profiling.

**Comment by rthbound** [comment]
@SamSaffron I see... Something more like:

**Comment by rthbound** [comment]
@SamSaffron I see... I've updated the PR to amend the comment rather than removing it entirely.

How's this?

**Comment by SamSaffron** [comment]
looks good to me! thanks

**Pull request merged**
