### PR TITLE
Angularjs compat

### PR DESCRIPTION
**Pull request by nathantsoi**
AngularJS compatibility

since is sometimes emptied before mini profiler can be initialized, we need to put the script tag in the head.

set ```Rack::MiniProfiler.config.inject_into = 'head'``` in config/initializers/mini_profiler.rb in your angular rails app

### CODE REVIEW

**Comment by nathantsoi** [comment]
Should be all set.

**Comment by SamSaffron** [comment]
sorry one last thing here, 

inject into should be a symbol eg `:head` or `:body` feels really odd as a string. can you change that?

**Comment by nathantsoi** [comment]
good call

**Comment by shanbhardwaj** [comment]
@nathantsoi @SamSaffron guys it would be great to have this working.

**Comment by nathantsoi** [comment]
@shanbhardwaj, I've fixed this by moving the ng-view declaration inside the body

**Comment by joshuaflanagan** [comment]
Sounds like this PR should be closed, and replaced with a caveat in the README directing people to use the workaround (stop making `body` your `ng-view`). Is that right?

**Comment by nathantsoi** [comment]
yep!

**Pull request closed without merging**
