### PR TITLE
Add mongo/mongoid5 support

### PR DESCRIPTION
**Pull request by nofxx**
Mongoid 5 dropped moped and it's using default mongo driver.
This adds  support for it. 

Note:
I'm using ActiveSupport's method_chain because Mongoid already requires it, may change if you want.

### CODE REVIEW

**Comment by SamSaffron** [comment]
sure, let try this out, thanks!

**Comment by nofxx** [comment]
@SamSaffron I missed something... =/

I was using all day yesterday `#inspect` which give all the info but it's a lil messy:

```
#<Mongo::Protocol::Query:0x0000000727c200 @database="database", @namespace="database.collections", @selector={"_id"=>"xxxxxx"}, @options={:project=>nil, :skip=>nil, :limit=>nil, :flags=>[:slave_ok]}, @project=nil, @skip=0, @limit=0, @flags=[:slave_ok]>   
```

Then I've found `#payload` and thought: hey, that's the proper way! let's commit:
But there's not even the collection =/

```
{:command_name=>"find", :database_name=>"db", :command=>{:filter=>{"_id"=>"xxxxxx"}, :project=>nil, :skip=>nil, :limit=>nil, :flags=>[:slave_ok]}, :request_id=>nil}   
```


Fixing a better inspect for this. Pushing today.
Sorry and thanks.

**Comment by nofxx** [comment]
Here's the `#payload` method:

https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/protocol/query.rb#L80

Even the comment says it's meant for debugging/monitoring. Did I get it wrong?
Not sure if Ishould I file a bug reporting it doesn't contains the collection name.

**Comment by nofxx** [comment]
Durran helped me on JIRA: 

https://jira.mongodb.org/browse/RUBY-1000

Implementing the new way.

**Comment by coin8086** [comment]
@nofxx I encountered a problem on the payload method you mentioned:

2016-03-23 23:24:26 - NoMethodError - undefined method `payload' for #<Mongo::Protocol::Query:0x00000003356cb0>:
	/home/robert/.rvm/gems/ruby-2.2.1/gems/rack-mini-profiler-0.9.9.2/lib/patches/db/mongo.rb:6:in `dispatch_with_timing'

It's in my Sinatra App with Mongo and Thin. When I turn off the profiler it's all right. It seems that the payload method is longer there. My MongoDB version is 3.0 and Ruby Mongo Driver is 2.0. Do I miss/mistake anything?

**Pull request merged**
