### PR TITLE
Allow environment variable to define sql patching

### PR DESCRIPTION
**Pull request by kbrock**
When users introduce their own patches, or want to work around
patch detection, this allows them to override with
`$RACK_MINI_PROFILER_PATCH`

setting to `"false"` skips sql patches all together

### CODE REVIEW

**Comment by kbrock** [comment]
failure fixed by #255

**Comment by SamSaffron** [comment]
I think this is fine, can you document this in the readme and if possible add a test case for it?

**Comment by kbrock** [comment]
1. added `README`
2. There are a number of test cases. any other one of interest
3. Modified `patch` to allow an initializer to pass particular ORM names.

**Comment by SamSaffron** [comment]
awesome, also love the doco

**Comment by kbrock** [comment]
thanks so much

**Pull request merged**
