### PR TITLE
Add host name and process id to server time output

### PR DESCRIPTION
**Pull request by jhicks**

### CODE REVIEW

**Comment by SamSaffron** [comment]
I am fine with this change but it is going to have to be opt in, adds a lot of noise to the UI in many cases.

**Comment by seanlinsley** [comment]
@jhicks ping

**Comment by kbrock** [comment]
@seanlinsley I'm confused with the ping.
This looks like a nice feature, but it adds too much noise for the average user.
So the request is: could you change this to add an option and make it opt in?

**Comment by kbrock** [comment]
Think test failure is bogus. Should be fixed by #255

**Comment by kbrock** [comment]
Also, could you include a before and after screen shot?
Thanks

**Comment by SamSaffron** [comment]
I am closing this, for me to accept this it is going to have to be an opt in thing :( sorry.

**Pull request closed without merging**
